<a href="https://colab.research.google.com/github/VictorHugofny/Redes-Neurais-Python/blob/main/perceptor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

dados_entrada = np.array([[0,0,1],
                         [1,1,1],
                         [1,0,1],
                         [0,1,1]])

saida_real = np.array ([[0,1,1,0]]).T


array([[0],
       [1],
       [1],
       [0]])

In [ ]:
np.random.seed(3)

In [ ]:
pesos_sinapticos = 2 * np.random.random((3,1)) - 1

In [ ]:
pesos_sinapticos

array([[ 0.10159581],
       [ 0.41629565],
       [-0.41819052]])

In [ ]:
pesos_sinapticos

array([[ 0.10159581],
       [ 0.41629565],
       [-0.41819052]])

Funcão de ativação sigmoide


In [ ]:
def sigmoide(x):
    return 1/(1+ np.exp(-x))

In [ ]:
def derivada_sigmoide(x):
    return x*(1-x)

In [ ]:
for i in range(1000):
    saida_estimada = sigmoide(np.dot(dados_entrada, pesos_sinapticos))
    erro = saida_real - saida_estimada
    ajuste = erro * derivada_sigmoide(saida_estimada)
    pesos_sinapticos += np.dot(dados_entrada.T, ajuste)

In [ ]:
saida_estimada

array([[8.59970552e-04],
       [9.99297925e-01],
       [9.99426963e-01],
       [7.01932421e-04]])